isd-sgcu/oph-67-frontend

src/app/(app)/profile/certificate/page.tsx, src/app/(app)/profile/page.tsx, src/components/profile/interested-item.tsx
fix: forgot to correct import path after rename components
=> fix: wrong import path

src/app/(app)/example/page.tsx, src/app/actions/example/example.ts
=> feat: add action example

src/app/(app)/profile/page.tsx, src/app/actions/profile/user.ts
Integrate get profile on qr-code page
=> feat: integrate profile

package.json, pnpm-lock.yaml, src/app/(admin)/admin/role/page.tsx, src/components/ui/dropdown-menu.tsx
=> fix: dropdown cn

src/app/(app)/middleware.ts, src/app/actions/auth.ts, src/app/actions/register/register-staff.ts, src/app/actions/register/register-user.ts, src/components/register/subpages/pdpa.tsx, src/hooks/use-auth.ts
=> feat: auth

src/app/actions/auth.ts, src/components/register/subpages/pdpa.tsx
=> fix: cookie set servr

src/app/actions/register/register-user.ts, src/components/register/subpages/userform-edit.tsx, src/components/register/subpages/userform.tsx, src/const/staff-year.ts
=> fix: birthDate added

src/app/actions/edit-profile/edit-profile.ts, src/app/actions/get-profile/get-user.ts, src/components/register/subpages/adminform-edit.tsx, src/components/register/subpages/userform-edit.tsx
- edit profile with real id and token
=> feat: real id and token

src/app/actions/edit-profile/edit-profile.ts, src/app/actions/get-profile/get-user.ts, src/components/register/subpages/adminform-edit.tsx, src/components/register/subpages/userform-edit.tsx
- มันมี admin-token กับ auth-token
=> fix: independent admin token

src/app/actions/register/register-user.ts
selectedSources
- formData.append(key, value.join(','))
=> fix: selected sources register

src/app/(admin)/3a9805a5/role/page.tsx, src/app/actions/staff/change-role.ts
=> feat: dropdown api

.github/workflows/pr.yml
=> feat(ci): run build in pr

src/app/(app)/profile/page.tsx, src/components/register/subpages/pdpa.tsx, src/middleware.ts, src/types/register.ts
=> Disable PDPA button

src/app/(app)/layout.tsx, src/app/actions/login/login.ts, src/components/auth/auth-provider.tsx
=> feat: auto login

src/components/homepage/footer.tsx, src/components/homepage/popup.tsx
=> Full HD img and new footer

src/app/(app)/layout.tsx, src/components/homepage/footer.tsx, src/components/homepage/navbar.tsx, src/components/homepage/popup.tsx, src/components/register/subpages/adminform-edit.tsx, src/components/register/subpages/adminform.tsx, src/components/register/subpages/userform-edit.tsx, src/components/register/subpages/userform.tsx
=> fix: full hd img

src/components/homepage/footer.tsx, src/components/register/subpages/adminform-edit.tsx, src/components/register/subpages/pdpa.tsx
- Move Ribbon
- แก้การ Edit Profile ของ Admin และ Staff ให้ไม่สามารถแก้ Status และคณะได้
=> Fix Footer UI + Edit Form Behavior

src/components/register/subpages/adminform-edit.tsx, src/components/register/subpages/userform-edit.tsx
=> fix: dup logo

src/middleware.ts
=> feat: add /profile/certificate to blockedPath in middleware

data/data-extraction.py, src/app/(admin)/layout.tsx, src/components/workshop/workshop-list.tsx, src/const/faculties.ts
=> fix: remove some faculties & Toaster

src/const/workshop-json.ts
=> fix: change location Workshop Cognitive

src/app/(app)/page.tsx, src/app/actions/evaluation/get-evaluation.ts, src/app/actions/evaluation/post-evaluation.ts, src/components/evaluation-form/subpages/form3.tsx, src/components/ui/label.tsx, src/types/evaluation-backed-interface.ts
- ปันกุไม่รุ้กุทำอะไรลงไป ถ้ามันเพิ่มงานให้มึงกุกราบขอโทด
=> feat: check eval

src/app/(app)/page.tsx, src/app/(app)/profile/page.tsx
=> feat: certificate check
